config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  authenticate :user do
    resources :journal_entries
  end

  root to: 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :user

  validates_presence_of :body, :entry_date
end

app/models/user.rb
class User < ApplicationRecord
  has_many :journal_entries

  # Include default devise modules. Others available are:
  # :confirmable, :lockable,
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :timeoutable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image_url = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.google_oauth2"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = 'http://localhost:3000'
  end
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :set_journal_entry, only: %i[ show edit update destroy ]

  # GET /journal_entries
  def index
    @journal_entries = current_user.journal_entries.all
  end

  # GET /journal_entries/1
  def show
  end

  # GET /journal_entries/new
  def new
    @journal_entry = current_user.journal_entries.new
  end

  # GET /journal_entries/1/edit
  def edit
  end

  # POST /journal_entries
  def create
    @journal_entry = current_user.journal_entries.new(journal_entry_params)

    if @journal_entry.save
      redirect_to @journal_entry, notice: "Journal entry was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /journal_entries/1
  def update
    if @journal_entry.update(journal_entry_params)
      redirect_to @journal_entry, notice: "Journal entry was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /journal_entries/1
  def destroy
    @journal_entry.destroy
    redirect_to journal_entries_url, notice: "Journal entry was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal_entry
      @journal_entry = JournalEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_entry_params
      params.require(:journal_entry).permit(:body, :entry_date)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/journal_entries/_form.html.erb
<%= form_with(model: journal_entry) do |form| %>
  <% if journal_entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(journal_entry.errors.count, "error") %> prohibited this journal_entry from being saved:</h2>

      <ul>
        <% journal_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :entry_date, class: "mb-2 block text-gray-700" %>
    <%= form.datetime_field :entry_date %>
  </div>

  <div class="mb-6">
    <%= form.label :body, class: "mb-2 block text-gray-700" %>
    <%= form.text_area :body, class: "bg-white rounded-md border border-gray-200 p-3 focus:outline-none w-full" %>
  </div>

  <div class="mb-6">
    <%= form.submit %>
  </div>
<% end %>

app/views/journal_entries/_journal_entry.html.erb
<section id="<%= dom_id journal_entry %>" class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-1 mx-auto">
    User: <%= journal_entry.user.email %>
    <h2 class="text-xl font-medium text-gray-700 title-font mb-2">
      <!-- 12 Jun 2019 -->
      <%= journal_entry.entry_date %>
    </h2>
    <p class="leading-relaxed">
      <%= journal_entry.body %>
    </p>
    <%= link_to 'Read More', journal_entry, class: "text-yellow-500 inline-flex items-center mt-4" %>
  </div>
</section>

app/views/journal_entries/edit.html.erb
<h1>Editing journal entry</h1>

<%= render "form", journal_entry: @journal_entry %>

<br>

<div>
  <%= link_to "Show this journal entry", @journal_entry %> |
  <%= link_to "Back to journal entries", journal_entries_path %>
</div>

app/views/journal_entries/index.html.erb
<h1>Journal entries</h1>

<%= link_to "New Journal Entry", new_journal_entry_path %>

<div id="journal_entries">
  <% @journal_entries.each do |journal_entry| %>
    <%= render journal_entry %>
  <% end %>
</div>

app/views/journal_entries/new.html.erb
<h1>New journal entry</h1>

<%= render "form", journal_entry: @journal_entry %>

<br>

<div>
  <%= link_to "Back to journal entries", journal_entries_path %>
</div>

app/views/journal_entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @journal_entry %>

<div>
  <%= link_to "Edit this journal entry", edit_journal_entry_path(@journal_entry) %> |
  <%= link_to "Back to journal entries", journal_entries_path %>

  <%= button_to "Destroy this journal entry", @journal_entry, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-gray-600 body-font bg-slate-100 mt-10">
  <div class="container px-5 py-24 mx-auto flex md:items-center lg:items-start md:flex-row md:flex-nowrap flex-wrap flex-col">
    <div class="w-64 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left">
      <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-yellow-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">Tailblocks</span>
      </a>
      <p class="mt-2 text-sm text-gray-500">Air plant banjo lyft occupy retro adaptogen indego</p>
    </div>
    <div class="flex-grow flex flex-wrap md:pl-20 -mb-10 md:mt-0 mt-10 md:text-left text-center">
      <div class="lg:w-1/3 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-600 hover:text-gray-800">First Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Second Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Third Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
          </li>
        </nav>
      </div>
      <div class="lg:w-1/3 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-600 hover:text-gray-800">First Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Second Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Third Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
          </li>
        </nav>
      </div>
      <div class="lg:w-1/3 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-600 hover:text-gray-800">First Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Second Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Third Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
          </li>
        </nav>
      </div>
    </div>
  </div>
  <div class="bg-gray-200">
    <div class="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row">
      <p class="text-gray-500 text-sm text-center sm:text-left">© 2020 Tailblocks —
        <a href="https://twitter.com/knyttneve" rel="noopener noreferrer" class="text-gray-600 ml-1" target="_blank">@knyttneve</a>
      </p>
      <span class="inline-flex sm:ml-auto sm:mt-0 mt-2 justify-center sm:justify-start">
        <a class="text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
          </svg>
        </a>
      </span>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="qa-header text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <%= link_to root_path, class:"flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" do %>
      <span class="ml-3 text-xl">Adventure Log</span>
    <% end %>

      <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
        <% if user_signed_in? %>
            <%= link_to 'Entires', journal_entries_path, class: "mr-5 hover:text-gray-900" %>
            <%= link_to 'Profile', edit_user_registration_path, class: "mr-5 hover:text-gray-900" %>
        <% else %>
            <%= link_to 'Features', root_path, class: "mr-5 hover:text-gray-900" %>
            <%= link_to 'About Us', root_path, class: "mr-5 hover:text-gray-900" %>
        <% end %>
      </nav>

    <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, class: "inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0" %>
    <% else %>
      <%= link_to 'Login', new_user_session_path, class: "inline-flex items-center justify-end bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0" %>
      <%= link_to 'Sign Up', new_user_registration_path, class: "inline-flex items-center justify-end bg-gray-100 border-0 ml-1 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0" %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdventureLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@200;400;600&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
      .debug_dump {
          background-color: #efefef;
          border-radius: 5px;
          display: block;
          font-size: 14px;
          margin: 50px 5px 5px 5px;
          padding: 10px 15px;
      }
    </style>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <main class="container mx-auto px-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>